name: Report a Bug
description: Help our dev team fix bugs
title: "BUG: "
labels: ["\U0001FAB2 Bug, Java"]
body:
  - type: textarea
    id: bug-desc
    attributes:
      label: Bug Description
      description: What happened ?
      placeholder: Tell us what you see and step to reproduce !
      value: "Here my bug description.... \
      \
      - Step 1 to reproduce \
      - Step 2 to reproduce \
      - Step 3 to reproduce \
      - ..."
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: What platforms are you seeing the problem on ?
      multiple: true
      options:
        - Linux
        - MacOS
        - Windows 11
        - Windows 10
        - Windows 8 or below
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: |
        ## Don't forget to add this issue to the "Bugs" project