name: Create a new feature
description: Describe a new feature to everyone
title: "FEATURE: "
labels: ["📝 Functionnality, Java"]
body:
  - type: textarea
    id: feature-desc
    attributes:
      label: Feature Description
      description: What do you add ?
      placeholder: Write here !
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Don't forget to add this issue to the "LoyaltyCard" project